### ISSUE TITLE
[Profile] View user's information

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#14]
Implement view user's information features

**Comment by hoainambmt** [comment]
@minhtridn2001 anh ơi viết API InfomationUser cho e, gồm những thuộc tính: image_profile, name, sex, phone, password, birthday, address

**Comment by minhtridn2001** [comment]
@hoainambmt  Lấy User info vào userId nhé em: 
* Url: api/v1/user/{userId}
* Method: GET
* Url param: `userId =[Integer]`
* Response: 
`return response()->json(array(
                'error' => false,
                'content' => $userInfo,
                'status_code' => 200
            ));`
Ví dụ:  
Request: http://192.168.1.16/web_app/public/api/v1/user/6
Response:  
{"error":false,"content":{"id":6,"name":"tri","email":"tri@gmail.com","phone":null,"birthday":null,"sex":null,"address":null,"user_status_type_id":null,"created_at":"2017-04-03 09:17:16","updated_at":"2017-04-03 09:17:16"},"status_code":200}

**Comment by hoainambmt** [comment]
Complete!

**Comment by minhtridn2001** [comment]
@hoainambmt Anh chưa thấy em commit?

**Comment by hoainambmt** [comment]
@minhtridn2001 hôm bữa cuối ngày e có commit mà sao nó chưa lên, h em commit lại rồi đó a 👍

**Comment by minhtridn2001** [comment]
👍 🍌
