### ISSUE TITLE
[Home] Show warning points

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#18]
Show warning points into map

**Comment by hoainambmt** [comment]
complete

**Comment by minhtridn2001** [comment]
Các chỗ cần sửa:  
- [ ] Thiếu javadoc, comment.
- [ ] Không đưa data cứng vào code, sử dụng constant hoặc lấy từ database:
'if(arrWarningPoint.get(i).getWarningTypeId() == 1){ // Không được code cứng typyId == 1
                                        bitmapdraw=(BitmapDrawable)getResources().getDrawable(R.drawable.mapmarker);
                                        b =bitmapdraw.getBitmap();
                                    }'  
=> Solution là thêm 1 cột icon_id vào table warning_type, chạy vòng lặp ứng với mỗi warning_type_id sẽ  lấy icon tương ứng.
- [ ] Trong model Warning: 'private Date startTime;', sửa Date lại thành Timestamp để phù hợp với column trong database.
- [ ] MainActivity line 809: 'arrWarningPoint = gson.fromJson(result.getString("content"), listType );'
=> Chỗ này sẽ có exception vì convert từ String qua Date, em cần set date formate bằng cách thêm gson.setDateFormat(...)
- [ ] MainActitivy line 622: 
'//schedule the timer, after the first 5000ms the TimerTask will run every 10000ms
        timerShowWarning.schedule(timerTaskShowWarning, 5000, 30000); //'  
Sao 30000 lại là 10000ms, đừng làm anh hoang mang @@

**Comment by hoainambmt** [comment]
Xong r a, a xem thử 💃

**Comment by minhtridn2001** [comment]
Good 👍
