### ISSUE TITLE
Web App screen definition documents

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#2]
Design Screen definition documents:
- [x] Home (Nam)
- [x] Realtime map (Active vehicle) (Vũ)
- [x] Driver(Tuan)
- [x] Vehicles(Tuan)
- [x] History (Nam)
- [x] Schedule (Vũ)

**Comment by minhtridn2001** [comment]
@hoainambmt Xong roi. Review nha

**Comment by hoainambmt** [comment]
@minhtridn2001 xong roi anh
