### ISSUE TITLE
[Home] Start/ complete journey functions

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#20]
Implement start journey and complete journey functions.

**Comment by tuanhwing** [comment]
Create API pls
Tên API: Get schedule
Chức năng API: lấy thông tin lịch trình của ngày hôm nay của tài xế theo id
Params: userid
Out put: schedule_id, Điểm kết thúc, thời gian bắt đầu và kết thúc dự kiến.

**Comment by tuanhwing** [comment]
Tạo giúp em API
Tên API: Get schedule
Chức năng API: lấy thông tin lịch trình của ngày hôm nay của tài xế theo id
Params: userid
Out put: schedule_id, Điểm kết thúc, thời gian bắt đầu và kết thúc dự kiến.

**Comment by minhtridn2001** [comment]
@tuanhwing done!
URL: api/v1/schedule/incoming/user/{userId} 
Method: GET

**Comment by tuanhwing** [comment]
Xong!
@minhtridn2001
