### ISSUE TITLE
[Home] Add warning

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#22]
Implement add warning function

**Comment by hoainambmt** [comment]
@minhtridn2001 viết cho e api warning type

**Comment by minhtridn2001** [comment]
@hoainambmt:
Em design giúp anh luôn nhé, gồm:
Tên: API
Chức năng API:
Params truyền vào:
Output:

**Comment by hoainambmt** [comment]
complete

**Comment by minhtridn2001** [comment]
Good 👍
