### ISSUE TITLE
[Schedule] Schedule list

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#23]
Implement incoming schedule and completed schedule lists

**Comment by CongVuUIT** [comment]
@minhtridn2001 Anh viết giúp em API cho cái Schedule với History.

**Comment by minhtridn2001** [comment]
@CongVuUIT Lấy list schedule dựa vào Driver_id nhé em: 
* Url: api/v1/schedule/user/{userId}
* Method: GET
* Url param: `userId=[Integer]`
* Response: 
`return response()->json(array(
                'error' => false,
                'content' => $resultList,
                'status_code' => 200
            ));`
Ví dụ:  
Request: http://192.168.1.16/web_app/public/api/v1/schedule/user/6  
Response:  
{"error":false,"content":[{"schedule_id":1,"driver_id":6,"vehicle_id":3,"intend_start_time":"2017-03-19 08:00:00","intend_end_time":"2017-03-19 22:00:00","location_lat_start":9.2346669999999999589590515824966132640838623046875,"location_long_start":102.4667429999999939127519610337913036346435546875,"location_lat_end":12.244566999999999978854248183779418468475341796875,"location_long_end":108.3555290000000042027750168927013874053955078125,"real_start_time":null,"real_end_time":null,"schedule_status_type_id":1,"device_id":"1234"}],"status_code":200}

**Comment by CongVuUIT** [comment]
@minhtridn2001 complete.

**Comment by minhtridn2001** [comment]
@CongVuUIT Em làm luôn phần History. Phân ra dựa vào status type nhé

**Comment by CongVuUIT** [comment]
@minhtridn2001 
Complete!!!
