### ISSUE TITLE
[Schedule] Schedule detail

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#24]
Implement schedule detail screen

**Comment by CongVuUIT** [comment]
@minhtridn2001 Complete!!!

**Comment by minhtridn2001** [comment]
@CongVuUIT :  1 số chỗ cần sửa:
- [x] Ko hiện status type ID, thay bằng status name.
- [x] Ko cần hiện thông tin toạ độ, device id.
- [x] Design giao diện lại cho bắt mắt hơn nha em.

**Comment by CongVuUIT** [comment]
@minhtridn2001 
Complete!!!
