### ISSUE TITLE
Create Entity Relationship Diagram

### ISSUE THREAD

**Issue by minhtridn2001** [efode-intership/VTS#3]
Create Entity Relationship Diagram

**Comment by hoainambmt** [comment]
#3

**Comment by minhtridn2001** [comment]
@hoainambmt @tuanhwing @CongVuUIT 
- Tách thêm entity để quản lý warningType.
- Warning cần có thêm thời gian bắt đầu và kết thúc.
- Entity Token cần có thêm trạng thái.
- Vehicle cần chi tiết hơn để quản lý được thông tin của xe.
- Driver, Vehicle và Schedule cần quản lý thêm trạng thái.
- Sẽ cần có thêm 1 bảng để quản lý thời gian làm việc của Driver.
- Schedule cần quản lý được: thời gian dự kiến bắt đầu, thời gian bắt đầu thực tế, thời gian kết thúc dự kiến và thực tế,...
- Bảng History có dư thừa hay không? Khi các cột có thể tính từ Schedule_active?

**Comment by minhtridn2001** [comment]
Thêm role Staff thì sửa lại ERD 1 tí. 1 Entity User chung, Driver và Staff kế thừa entity này nhé.
