### ISSUE TITLE
[Home] Show other vehicles sometime have exception when click marker.

### ISSUE THREAD

**Issue by hoainambmt** [efode-intership/VTS#40]
![screenshot 229](https://cloud.githubusercontent.com/assets/16558871/25420511/9db23ae4-2a82-11e7-9008-9fdb98800150.png)

**Comment by CongVuUIT** [comment]
@minhtridn2001  @hoainambmt @tuanhwing 
•	Để tránh exception dẫn đến dừng chương trình thì nên xét điều kiện isFinishing() trước khi show dialog. Ví dụ:
runOnUiThread(new Runnable() {
    @Override
    public void run() {
        if (!MainActivity.this.isFinishing()) {
            dialogCallOtherVehicles.show();
        }
    }
});

•	Khi sử dụng timer thì cần gọi hàm stopTimerTask() trong onDestroy để khi Signout thì timer sẽ được stop và khi ta login vào lại thì sẽ chạy timer mới. Nếu không stop timer thì khi signout và login vô lại sẽ có 2 timer được chạy dẫn đến bug. Ví dụ:
-	Hàm stopTimerTask(): 
public void stopShowOtherVehicleTimerTask() {
        Log.d("MainActivity", new Object(){}.getClass().getEnclosingMethod().getName());
        if (timerShowOtherVehicles != null) {
            timerShowOtherVehicles.cancel();
            timerShowOtherVehicles = null;
        }
    }
-	Gọi hàm trong onDestroy:

@Override
protected void onDestroy() {
    super.onDestroy();
        stopShowOtherVehicleTimerTask();
       }
